# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: flutter_ci

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    name: run testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install dependencies
        uses: geowatson/flutter-latest@1.0.0
        with:
          args: pub get

      - name: run tests
        uses: geowatson/flutter-latest@1.0.0
        with:
          args: test